apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rk8s8yr3y-nodejs 
  janus-idp.io/tekton: rk8s8yr3y-nodejs
  backstage.io/kubernetes-id: rk8s8yr3y-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rk8s8yr3y-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  