apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rk8s8yr3y-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rk8s8yr3y-nodejs 
  name: rk8s8yr3y-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: rk8s8yr3y-nodejs 
